// app/layout.tsx
import "./globals.css";
import "@mantine/core/styles.css";
import type { Metadata } from "next";
import { Providers } from "./providers/Providers";
import { ColorSchemeScript } from "@mantine/core";
import { ReduxProvider } from "./providers/ReduxProvider";
import { ThemeSyncer } from "./ThemeSync";
import { Toaster } from "sonner";
import { ModalRenderer } from "@/components/modals/ModalRenderer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body className="!bg-background">
        <ReduxProvider>
          <Providers>
            {/* <ThemeSyncer /> */}
            <main>{children}</main>
            <Toaster
              position="bottom-right"
              richColors
              toastOptions={{
                style: {
                  background: "var(--background)",
                  border: "none",
                },
                classNames: {
                  toast: "glass-card",
                  title: "font-medium text-sm",
                  description: " text-xs",
                },
              }}
            />
            <ModalRenderer />
          </Providers>
        </ReduxProvider>
      </body>
    </html>
  );
}
