"use client";
import React, { useState } from "react";
import { Button } from "@/components/ui/button";
import { X, Trash2, AlertTriangle, FileText, Edit3, Settings2 } from "lucide-react";

interface DeleteReportModalProps {
  open: boolean;
  onClose: () => void;
  report: any;
  onDeleteWithTasks: () => Promise<void>;
  onDeleteKeepTasks: () => Promise<void>;
  onEditAssignments?: () => void;
}

export default function DeleteReportModal({
  open,
  onClose,
  report,
  onDeleteWithTasks,
  onDeleteKeepTasks,
  onEditAssignments,
}: DeleteReportModalProps) {
  const [isDeleting, setIsDeleting] = useState(false);
  const [selectedOption, setSelectedOption] = useState<"with-tasks" | "keep-tasks" | "edit-assignments" | null>(null);

  if (!open) return null;

  const reportTitle = report?.displayTitle || report?.reportId || "this report";
  const taskCount = report?.summary?.totalTasks || 
    report?.meta?.summary?.totalTasks ||
    report?.suggestionsCreated || 
    report?.meta?.suggestionsCreated ||
    (report?.assignmentSuggestions || []).length ||
    "?";

  const handleDelete = async () => {
    if (!selectedOption) return;
    
    if (selectedOption === "edit-assignments") {
      onClose();
      if (onEditAssignments) {
        onEditAssignments();
      }
      return;
    }
    
    setIsDeleting(true);
    try {
      if (selectedOption === "with-tasks") {
        await onDeleteWithTasks();
      } else {
        await onDeleteKeepTasks();
      }
      onClose();
    } catch (e) {
      console.error("Delete failed:", e);
    } finally {
      setIsDeleting(false);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-black/60 backdrop-blur-sm"
        onClick={onClose}
      />
      
      {/* Modal */}
      <div className="relative w-full max-w-lg mx-4 bg-neutral-900/95 backdrop-blur-xl border border-white/10 rounded-2xl shadow-2xl overflow-hidden">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-white/10">
          <div className="flex items-center gap-3">
            <div className="h-10 w-10 rounded-lg bg-red-500/20 flex items-center justify-center">
              <AlertTriangle className="h-5 w-5 text-red-400" />
            </div>
            <div>
              <h2 className="text-lg font-semibold text-white">Delete Report</h2>
              <p className="text-sm text-neutral-400">This action cannot be undone</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="h-8 w-8 rounded-lg bg-white/5 hover:bg-white/10 flex items-center justify-center transition-colors cursor-pointer"
          >
            <X className="h-4 w-4 text-neutral-400" />
          </button>
        </div>

        {/* Content */}
        <div className="px-6 py-5 space-y-4">
          <p className="text-neutral-300 text-sm">
            You are about to delete <span className="text-white font-medium">"{reportTitle}"</span>
            {taskCount !== "?" && (
              <span> which contains <span className="text-amber-400 font-medium">{taskCount} tasks</span></span>
            )}.
          </p>
          
          <p className="text-neutral-400 text-sm">
            What would you like to do with the tasks generated by this report?
          </p>

          {/* Options */}
          <div className="space-y-3 pt-2">
            {/* Option 1: Delete with tasks */}
            <button
              onClick={() => setSelectedOption("with-tasks")}
              className={`w-full p-4 rounded-xl border transition-all cursor-pointer text-left ${
                selectedOption === "with-tasks"
                  ? "border-red-500/50 bg-red-500/10"
                  : "border-white/10 bg-white/5 hover:bg-white/10 hover:border-white/20"
              }`}
            >
              <div className="flex items-start gap-3">
                <div className={`h-8 w-8 rounded-lg flex items-center justify-center flex-shrink-0 ${
                  selectedOption === "with-tasks" ? "bg-red-500/20" : "bg-white/10"
                }`}>
                  <Trash2 className={`h-4 w-4 ${selectedOption === "with-tasks" ? "text-red-400" : "text-neutral-400"}`} />
                </div>
                <div>
                  <div className={`font-medium ${selectedOption === "with-tasks" ? "text-red-300" : "text-white"}`}>
                    Delete report and all tasks
                  </div>
                  <div className="text-sm text-neutral-400 mt-1">
                    Permanently remove this report and all {taskCount !== "?" ? taskCount : "associated"} tasks from the database. 
                    Tasks will be removed from all sprints and backlogs.
                  </div>
                </div>
              </div>
            </button>

            {/* Option 2: Edit assignments first */}
            <button
              onClick={() => setSelectedOption("edit-assignments")}
              className={`w-full p-4 rounded-xl border transition-all cursor-pointer text-left ${
                selectedOption === "edit-assignments"
                  ? "border-emerald-500/50 bg-emerald-500/10"
                  : "border-white/10 bg-white/5 hover:bg-white/10 hover:border-white/20"
              }`}
            >
              <div className="flex items-start gap-3">
                <div className={`h-8 w-8 rounded-lg flex items-center justify-center flex-shrink-0 ${
                  selectedOption === "edit-assignments" ? "bg-emerald-500/20" : "bg-white/10"
                }`}>
                  <Settings2 className={`h-4 w-4 ${selectedOption === "edit-assignments" ? "text-emerald-400" : "text-neutral-400"}`} />
                </div>
                <div>
                  <div className={`font-medium ${selectedOption === "edit-assignments" ? "text-emerald-300" : "text-white"}`}>
                    Review & edit assignments first
                  </div>
                  <div className="text-sm text-neutral-400 mt-1">
                    Open the assignment review modal to choose which task suggestions to keep, approve, or remove before making a decision.
                  </div>
                </div>
              </div>
            </button>

            {/* Option 3: Keep tasks */}
            <button
              onClick={() => setSelectedOption("keep-tasks")}
              className={`w-full p-4 rounded-xl border transition-all cursor-pointer text-left ${
                selectedOption === "keep-tasks"
                  ? "border-blue-500/50 bg-blue-500/10"
                  : "border-white/10 bg-white/5 hover:bg-white/10 hover:border-white/20"
              }`}
            >
              <div className="flex items-start gap-3">
                <div className={`h-8 w-8 rounded-lg flex items-center justify-center flex-shrink-0 ${
                  selectedOption === "keep-tasks" ? "bg-blue-500/20" : "bg-white/10"
                }`}>
                  <Edit3 className={`h-4 w-4 ${selectedOption === "keep-tasks" ? "text-blue-400" : "text-neutral-400"}`} />
                </div>
                <div>
                  <div className={`font-medium ${selectedOption === "keep-tasks" ? "text-blue-300" : "text-white"}`}>
                    Delete report only, keep tasks
                  </div>
                  <div className="text-sm text-neutral-400 mt-1">
                    Remove the report but keep all generated tasks. 
                    You can continue to modify and assign these tasks normally.
                  </div>
                </div>
              </div>
            </button>
          </div>
        </div>

        {/* Footer */}
        <div className="flex items-center justify-end gap-3 px-6 py-4 border-t border-white/10 bg-white/[0.02]">
          <Button
            onClick={onClose}
            variant="outline"
            className="border border-neutral-600/50 bg-neutral-800/30 text-neutral-300 hover:bg-neutral-700/50 hover:border-neutral-500 transition-all duration-200 cursor-pointer"
            disabled={isDeleting}
          >
            Cancel
          </Button>
          <Button
            onClick={handleDelete}
            disabled={!selectedOption || isDeleting}
            className={`cursor-pointer transition-all duration-200 ${
              selectedOption === "with-tasks"
                ? "border border-rose-500/50 bg-rose-500/10 text-rose-400 hover:bg-rose-500/20 hover:border-rose-400 hover:shadow-[0_0_12px_rgba(244,63,94,0.3)]"
                : selectedOption === "keep-tasks"
                ? "border border-blue-500/50 bg-blue-500/10 text-blue-400 hover:bg-blue-500/20 hover:border-blue-400 hover:shadow-[0_0_12px_rgba(59,130,246,0.3)]"
                : selectedOption === "edit-assignments"
                ? "border border-emerald-500/50 bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 hover:border-emerald-400 hover:shadow-[0_0_12px_rgba(16,185,129,0.3)]"
                : "border border-neutral-600/50 bg-neutral-800/30 text-neutral-500"
            }`}
          >
            {isDeleting ? (
              <>
                <span className="animate-spin mr-2">⏳</span>
                Deleting...
              </>
            ) : selectedOption === "with-tasks" ? (
              "Delete Report & Tasks"
            ) : selectedOption === "keep-tasks" ? (
              "Delete Report Only"
            ) : selectedOption === "edit-assignments" ? (
              "Review Assignments"
            ) : (
              "Select an option"
            )}
          </Button>
        </div>
      </div>
    </div>
  );
}
